# Controllers pour le frontend
controllers:
    resource:
        path: ../src/Controller
        namespace: App\Controller
    type: attribute

# API Platform (pour l'administration)
api_platform:
    resource: .
    type: api_platform
    prefix: /api
