nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173'] # Votre port React exact
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_credentials: true # TRÃˆS IMPORTANT pour "credentials: include"
            max_age: 3600
